blog_blog_homepage:
    path:     /admin
    defaults: { _controller: BlogBlogBundle:Blog:admin }
blog_blog_supprimer:
    path:     /admin/supprimer/{id}
    defaults: { _controller: BlogBlogBundle:Blog:supprimer }
blog_blog_com:
    path:     /com/{idArticle}
    defaults: { _controller: BlogBlogBundle:Blog:com }
    
